### ISSUE TITLE
[FEAT] API 명세 정리

### ISSUE THREAD

**Issue by MunSeongKim** [wisestudy/wisestudy-server#44]
**개발 이슈 내용**
- API 명세 정리
  - API 명 변경: 복수 명사 단어 수정
  - 비노출 API 처리: 카테고리 목록 조회 외 API, 관계를 위한 기능에 대한 것들
  - GlobalErrorHandler 적용: 에러 처리 핸들러 적용
    - 처리 에러 코드: 401, 404, 422, 500, 503

**진행사항**
- [x] API명 변경 : 복수 명사 단어 수정
- [x] 비노출 API 처리 
- [x] GlobalErrorHandler 적용
> - study_member API 
> - API에서 불필요한 method 제거

**예상완료일**
- 20.08.01

- 20.08.07
> - global_error_handler

**Comment by taxijjang** [comment]
완료
