### ISSUE TITLE
[FEAT]안드로이드 요구사항에 따른 schedule에 study title추가와 datefield -> datetimefield로 변경

### ISSUE THREAD

**Issue by taxijjang** [wisestudy/wisestudy-server#72]
**개발 이슈 내용**
- 안드로이드 요구사항에 따른 schedule에 study title추가와 datefield -> datetimefield로 변경

**진행사항**
- [x] schedule에 study title 추가
- [x] datefield -> datetimefield로 변경

**예상완료일**
- 20.08.11

**Comment by taxijjang** [comment]
완료

**Comment by taxijjang** [comment]
@jonghyunH 종현아 api 보고 생각했던데로 수정 됬으면 issue 클로즈해줘

**Comment by jonghyunH** [comment]
네네
